# 2.3 Lab Introduction To R

ISLR - Page 42

In [1]:
x <- c(1,3,2,5)

In [2]:
x

[1] 1 3 2 5

In [3]:
x[1]

[1] 1

In [4]:
x[0]

numeric(0)

In [12]:
x = c(1,6,2)

In [13]:
x

[1] 1 6 2

In [14]:
y = c(1,4,3)

In [15]:
y

[1] 1 4 3

In [16]:
length(x)

[1] 3

In [17]:
length(y)

[1] 3

In [18]:
x + y

[1]  2 10  5

In [19]:
ls()

[1] "x" "y"

In [21]:
?matrix

matrix                  package:base                   R Documentation

_M_a_t_r_i_c_e_s

_D_e_s_c_r_i_p_t_i_o_n:

     ‘matrix’ creates a matrix from the given set of values.

     ‘as.matrix’ attempts to turn its argument into a matrix.

     ‘is.matrix’ tests if its argument is a (strict) matrix.

_U_s_a_g_e:

     matrix(data = NA, nrow = 1, ncol = 1, byrow = FALSE,
            dimnames = NULL)
     
     as.matrix(x, ...)
     ## S3 method for class 'data.frame'
     as.matrix(x, rownames.force = NA, ...)
     
     is.matrix(x)
     
_A_r_g_u_m_e_n_t_s:

    data: an optional data vector (including a list or ‘expression’
          vector).  Non-atomic classed R objects are coerced by
          ‘as.vector’ and all attributes discarded.

    nrow: the desired number of rows.

    ncol: the desired number of columns.

   byrow: logical. If ‘FALSE’ (the default) the matrix is filled by
          columns, otherwise the matrix is filled by rows.

dimnames: A ‘dimnames’ attribute for the matrix: ‘NULL’ or a ‘list’ of
          length 2 giving the row and column names respectively.  An
          empty list is treated as ‘NULL’, and a list of length one as
          row names.  The list can be named, and the list names will be
          used as names for the dimensions.

       x: an R object.

     ...: additional arguments to be passed to or from methods.

rownames.force: logical indicating if the resulting matrix should have
          character (rather than ‘NULL’) ‘rownames’.  The default,
          ‘NA’, uses ‘NULL’ rownames if the data frame has ‘automatic’
          row.names or for a zero-row data frame.

_D_e_t_a_i_l_s:

     If one of ‘nrow’ or ‘ncol’ is not given, an attempt is made to
     infer it from the length of ‘data’ and the other parameter.  If
     neither is given, a one-column matrix is returned.

     If there are too few elements in ‘data’ to fill the matrix, then
     the elements in ‘data’ are recycled.  If ‘data’ has length zero,
     ‘NA’ of an appropriate type is used for atomic vectors (‘0’ for
     raw vectors) and ‘NULL’ for lists.

     ‘is.matrix’ returns ‘TRUE’ if ‘x’ is a vector and has a ‘"dim"’
     attribute of length 2 and ‘FALSE’ otherwise.  Note that a
     ‘data.frame’ is *not* a matrix by this test.  The function is
     generic: you can write methods to handle specific classes of
     objects, see InternalMethods.

     ‘as.matrix’ is a generic function.  The method for data frames
     will return a character matrix if there is only atomic columns and
     any non-(numeric/logical/complex) column, applying ‘as.vector’ to
     factors and ‘format’ to other non-character columns.  Otherwise,
     the usual coercion hierarchy (logical < integer < double <
     complex) will be used, e.g., all-logical data frames will be
     coerced to a logical matrix, mixed logical-integer will give a
     integer matrix, etc.

     The default method for ‘as.matrix’ calls ‘as.vector(x)’, and hence
     e.g. coerces factors to character vectors.

     When coercing a vector, it produces a one-column matrix, and
     promotes the names (if any) of the vector to the rownames of the
     matrix.

     ‘is.matrix’ is a primitive function.

     The ‘print’ method for a matrix gives a rectangular layout with
     dimnames or indices.  For a list matrix, the entries of length not
     one are printed in the form ‘integer,7’ indicating the type and
     length.

_N_o_t_e:

     If you just want to convert a vector to a matrix, something like
     
       dim(x) <- c(nx, ny)
       dimnames(x) <- list(row_names, col_names)

     will avoid duplicating ‘x’.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

_S_e_e _A_l_s_o:

     ‘data.matrix’, which attempts to convert to a numeric matrix.

     A matrix is the special case of a two-dimensional ‘array’.

_E_x_a

In [22]:
x = matrix(data=c(1,2,3,4), nrow=2, ncol=2)

In [23]:
x

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [24]:
x = matrix(c(1,2,3,4), 2, 2)

In [25]:
x

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [26]:
sqrt(x)

[,1]     [,2]    
[1,] 1.000000 1.732051
[2,] 1.414214 2.000000

In [27]:
x**2

[,1] [,2]
[1,] 1     9  
[2,] 4    16

In [28]:
?rnorm

Normal                  package:stats                  R Documentation

_T_h_e _N_o_r_m_a_l _D_i_s_t_r_i_b_u_t_i_o_n

_D_e_s_c_r_i_p_t_i_o_n:

     Density, distribution function, quantile function and random
     generation for the normal distribution with mean equal to ‘mean’
     and standard deviation equal to ‘sd’.

_U_s_a_g_e:

     dnorm(x, mean = 0, sd = 1, log = FALSE)
     pnorm(q, mean = 0, sd = 1, lower.tail = TRUE, log.p = FALSE)
     qnorm(p, mean = 0, sd = 1, lower.tail = TRUE, log.p = FALSE)
     rnorm(n, mean = 0, sd = 1)
     
_A_r_g_u_m_e_n_t_s:

    x, q: vector of quantiles.

       p: vector of probabilities.

       n: number of observations. If ‘length(n) > 1’, the length is
          taken to be the number required.

    mean: vector of means.

      sd: vector of standard deviations.

log, log.p: logical; if TRUE, probabilities p are given as log(p).

lower.tail: logical; if TRUE (default), probabilities are P[X <= x]
          otherwise, P[X > x].

_D_e_t_a_i_l_s:

     If ‘mean’ or ‘sd’ are not specified they assume the default values
     of ‘0’ and ‘1’, respectively.

     The normal distribution has density

            f(x) = 1/(sqrt(2 pi) sigma) e^-((x - mu)^2/(2 sigma^2))     
     
     where mu is the mean of the distribution and sigma the standard
     deviation.

_V_a_l_u_e:

     ‘dnorm’ gives the density, ‘pnorm’ gives the distribution
     function, ‘qnorm’ gives the quantile function, and ‘rnorm’
     generates random deviates.

     The length of the result is determined by ‘n’ for ‘rnorm’, and is
     the maximum of the lengths of the numerical arguments for the
     other functions.

     The numerical arguments other than ‘n’ are recycled to the length
     of the result.  Only the first elements of the logical arguments
     are used.

     For ‘sd = 0’ this gives the limit as ‘sd’ decreases to 0, a point
     mass at ‘mu’.  ‘sd < 0’ is an error and returns ‘NaN’.

_S_o_u_r_c_e:

     For ‘pnorm’, based on

     Cody, W. D. (1993) Algorithm 715: SPECFUN - A portable FORTRAN
     package of special function routines and test drivers.  _ACM
     Transactions on Mathematical Software_ *19*, 22-32.

     For ‘qnorm’, the code is a C translation of

     Wichura, M. J. (1988) Algorithm AS 241: The percentage points of
     the normal distribution.  _Applied Statistics_, *37*, 477-484.

     which provides precise results up to about 16 digits.

     For ‘rnorm’, see RNG for how to select the algorithm and for
     references to the supplied methods.

_R_e_f_e_r_e_n_c_e_s:

     Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) _The New S
     Language_.  Wadsworth & Brooks/Cole.

     Johnson, N. L., Kotz, S. and Balakrishnan, N. (1995) _Continuous
     Univariate Distributions_, volume 1, chapter 13.  Wiley, New York.

_S_e_e _A_l_s_o:

     Distributions for other standard distributions, including ‘dlnorm’
     for the _Log_normal distribution.

_E_x_a_m_p_l_e_s:

     require(graphics)
     
     dnorm(0) == 1/sqrt(2*pi)
     dnorm(1) == exp(-1/2)/sqrt(2*pi)
     dnorm(1) == 1/sqrt(2*pi*exp(1))
     
     ## Using "log = TRUE" for an extended range :
     par(mfrow = c(2,1))
     plot(function(x) dnorm(x, log = TRUE), -60, 50,
          main = "log { Normal density }")
     curve(log(dnorm(x)), add = TRUE, col = "red", lwd = 2)
     mtext("dnorm(x, log=TRUE)", adj = 0)
     mtext("log(dnorm(x))", col = "red", adj = 1)
     
     plot(function(x) pnorm(x, log.p = TRUE), -50, 10,
          main = "log { Normal Cumulative }")
     curve(log(pnorm(x)), add = TRUE, col = "red", lwd = 2)
     mtext("pnorm(x, log=TRUE)", adj = 0)
     mtext("log(pnorm(x))", col = "red", adj = 1)
     
     ## if you want the so-called 'error function'
     erf <- function(x) 2 * pnorm(x * sqrt(2)) - 1
     ## (see Abramowitz and Stegun 29.2.29)
     ## and the so-called 'complementary error function'
     erfc <- 

In [29]:
x = rnorm(50)

In [30]:
x

[1]  0.80049906 -1.09445641  0.47995707 -1.71508294 -0.76250148  0.03823836
 [7] -0.77880224 -1.16234733 -0.88347831 -0.98576096  0.02409604 -0.31789133
[13]  0.78356366  0.99908369  0.51178079 -0.49461977  1.97231370  0.16316395
[19] -0.48688510 -0.34586575 -1.96081878 -1.82695044  0.60706250 -0.24933007
[25]  0.27659675 -1.95972349  1.45439863 -1.70121846 -1.09269278 -0.60782853
[31]  0.13780904 -1.99515020  0.29539892  0.15269493 -0.12667988  1.84556927
[37] -1.05075257 -1.40665554  1.20194349 -0.57956014  0.89354357 -0.53907399
[43]  1.65312865 -0.50833218  1.20179433  1.80588198  0.39572318 -0.96633431
[49]  0.17257759 -1.25833247

In [31]:
y = x + rnorm(50, mean=50, sd=0.1)

In [32]:
cor(x,y)

[1] 0.9961385